input_boolean:
  afval_monitoring:
    name: Afval monitoring
    icon: mdi:information-outline

template:
  - binary_sensor:
      - name: Afval alarm actief
        state: "{{ not is_state('sensor.afvalinfo_westerlee_trash_type_today', 'geen') and is_state('input_boolean.afval_monitoring', 'on') }}"
        availability: "{{ states('sensor.afvalinfo_westerlee_trash_type_today') not in ['unavailable', 'unknown', 'none'] }}"

sensor:
  - platform: template
    sensors:
      afval_informatie_alarm_actief:
        friendly_name: "Afval alarm actief"
        value_template: "{{ is_state('binary_sensor.afval_alarm_actief', 'on') }}"
        availability_template: "{{ states('binary_sensor.afval_alarm_actief') not in ['unavailable', 'unknown'] }}"

      afval_monitormelding:
        friendly_name: "Afval monitormelding"
        value_template: >
          {% if is_state('binary_sensor.afval_alarm_actief', 'on') %}
            Afvalcontainer {{ states('sensor.afvalinfo_westerlee_trash_type_today') }} wordt vandaag geleegd! \
            Tijdstip: {{ as_timestamp(states.binary_sensor.afval_alarm_actief.last_changed) | timestamp_custom('%A %I:%M%p (%d-%b-%Y)') }}
          {% else %}
            Geen alarm actief
          {% endif %}
        availability_template: "{{ is_state('binary_sensor.afval_alarm_actief', 'on') }}"

alert:
  afval_informatie_alarm_actief:
    name: Afval alarm actief
    entity_id: binary_sensor.afval_alarm_actief
    state: "on"
    repeat:
      - 15
      - 30
      - 60
      - 120
    can_acknowledge: true
    skip_first: true
    title: "Informatie - Afvalalarm actief"
    message: >
      Afvalcontainer {{ states('sensor.afvalinfo_westerlee_trash_type_today') }} wordt vandaag geleegd! \
      Tijdstip: {{ as_timestamp(states.binary_sensor.afval_alarm_actief.last_changed) | timestamp_custom('%A %I:%M%p (%d-%b-%Y)') }}
    done_message: "Afvalalarm HERSTELD op {{ as_timestamp(states.binary_sensor.afval_alarm_actief.last_changed) | timestamp_custom('%A %I:%M%p (%d-%b-%Y)') }}"
    notifiers:
      - STD_Information  # Zorg ervoor dat de juiste notifier is geselecteerd
