input_boolean:
  test_batterij_monitoring:
    name: Test batterij monitoring
    #icon: mdi:alert
    icon: mdi:alert-circle-outline # warning
    # icon: mdi:information-outline 

input_number:
  test_batterij:
    name: Test batterij
    initial: 3.12
    min: 0
    max: 5
    step: 0.01
    mode: slider
    unit_of_measurement: "V"
    
template:
  - binary_sensor:
      - name: Test batterij alarm actief
        state: "{{ (states('input_number.test_batterij') | float(0) < 2.95) and is_state('input_boolean.test_batterij_monitoring', 'on') }}"
        availability: "{{ states('input_number.test_batterij') not in ['unavailable', 'unknown', 'none'] }}"

# Deze binaire sensor zal TRUE zijn als:
#
#    input_number.test_batterij lager dan 2.95V is.
#    input_boolean.test_batterij_monitoring ingeschakeld is.

# dashboard monitormelding, format name: "??? monitormelding"
sensor:
  - platform: template
    sensors:
      test_batterij_monitormelding:
        friendly_name: "Test batterij monitormelding"
        value_template: >
          {% if is_state('binary_sensor.test_batterij_alarm_actief', 'on') %}
            Testbatterij is {{ states('input_number.test_batterij') }} Volt,
            update: {{ as_timestamp(states.binary_sensor.test_batterij_alarm_actief.last_changed) | timestamp_custom('%d-%m-%Y om %H:%M') }}
          {% else %}
            Geen alarm actief
          {% endif %}
        availability_template: >
          {{ states('binary_sensor.test_batterij_alarm_actief') not in ['unavailable', 'unknown'] }}

alert:
  test_waarschuwing_alarm_actief:
    name: Test batterij alarm actief
    entity_id: binary_sensor.test_batterij_alarm_actief
    state: "on"
    repeat:
      - 15
      - 30
      - 60
      - 120
    can_acknowledge: true
    skip_first: true
    title: "Waarschuwing alarm - Test batterij"
    message: >
      Test is {{ states('input_number.test_batterij') }} Volt, 
      update: {{ as_timestamp(states.binary_sensor.test_batterij_alarm_actief.last_changed) | timestamp_custom('%d-%m-%Y om %H:%M') }}
    done_message: "Test batterij HERSTELD op {{ as_timestamp(states.binary_sensor.test_batterij_alarm_actief.last_changed) | timestamp_custom('%d-%m-%Y om %H:%M') }}"
    notifiers:
      - STD_Critical
      #- STD_Warning
      #- STD_Information